<?php
namespace Neos\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your needs! This block will be used as the migration description if getDescription() is not used.
 */
class Version20170913102707 extends AbstractMigration
{

    /**
     * @return string
     */
    public function getDescription()
    {
        return '';
    }

    /**
     * @param Schema $schema
     * @return void
     */
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on "mysql".');

        $this->addSql('ALTER TABLE wegmeister_tagmanager_domain_model_tag DROP FOREIGN KEY FK_68BA433790DA8F85');
        $this->addSql('DROP INDEX IDX_68BA433790DA8F85 ON wegmeister_tagmanager_domain_model_tag');
        $this->addSql('DROP INDEX flow_identity_wegmeister_tagmanager_domain_model_tag ON wegmeister_tagmanager_domain_model_tag');
        $this->addSql('ALTER TABLE wegmeister_tagmanager_domain_model_tag CHANGE groupname `group` VARCHAR(40) DEFAULT NULL');
        $this->addSql('ALTER TABLE wegmeister_tagmanager_domain_model_tag ADD CONSTRAINT FK_68BA43376DC044C5 FOREIGN KEY (`group`) REFERENCES wegmeister_tagmanager_domain_model_group (persistence_object_identifier)');
        $this->addSql('CREATE INDEX IDX_68BA43376DC044C5 ON wegmeister_tagmanager_domain_model_tag (`group`)');
        $this->addSql('CREATE UNIQUE INDEX flow_identity_wegmeister_tagmanager_domain_model_tag ON wegmeister_tagmanager_domain_model_tag (name, `group`)');
    }

    /**
     * @param Schema $schema
     * @return void
     */
    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on "mysql".');

        $this->addSql('ALTER TABLE wegmeister_tagmanager_domain_model_tag DROP FOREIGN KEY FK_68BA43376DC044C5');
        $this->addSql('DROP INDEX IDX_68BA43376DC044C5 ON wegmeister_tagmanager_domain_model_tag');
        $this->addSql('DROP INDEX flow_identity_wegmeister_tagmanager_domain_model_tag ON wegmeister_tagmanager_domain_model_tag');
        $this->addSql('ALTER TABLE wegmeister_tagmanager_domain_model_tag CHANGE `group` groupname VARCHAR(40) DEFAULT NULL COLLATE utf8_unicode_ci');
        $this->addSql('ALTER TABLE wegmeister_tagmanager_domain_model_tag ADD CONSTRAINT FK_68BA433790DA8F85 FOREIGN KEY (groupname) REFERENCES wegmeister_tagmanager_domain_model_group (persistence_object_identifier)');
        $this->addSql('CREATE INDEX IDX_68BA433790DA8F85 ON wegmeister_tagmanager_domain_model_tag (groupname)');
        $this->addSql('CREATE UNIQUE INDEX flow_identity_wegmeister_tagmanager_domain_model_tag ON wegmeister_tagmanager_domain_model_tag (name, groupname)');
    }
}
