<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your needs! This block will be used as the migration description if getDescription() is not used.
 */
class Version20160610173807 extends AbstractMigration
{

    /**
     * @return string
     */
    public function getDescription() {
        return '';
    }

    /**
     * @param Schema $schema
     * @return void
     */
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on "mysql".');

        $this->addSql('CREATE TABLE wegmeister_tagmanager_domain_model_group (persistence_object_identifier VARCHAR(40) NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE wegmeister_tagmanager_domain_model_tag (persistence_object_identifier VARCHAR(40) NOT NULL, `group` VARCHAR(40) DEFAULT NULL, name VARCHAR(255) NOT NULL, INDEX IDX_68BA43376DC044C5 (`group`), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB');
        $this->addSql('ALTER TABLE wegmeister_tagmanager_domain_model_tag ADD CONSTRAINT FK_68BA43376DC044C5 FOREIGN KEY (`group`) REFERENCES wegmeister_tagmanager_domain_model_group (persistence_object_identifier)');
    }

    /**
     * @param Schema $schema
     * @return void
     */
    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on "mysql".');

        $this->addSql('ALTER TABLE wegmeister_tagmanager_domain_model_tag DROP FOREIGN KEY FK_68BA43376DC044C5');
        $this->addSql('DROP TABLE wegmeister_tagmanager_domain_model_group');
        $this->addSql('DROP TABLE wegmeister_tagmanager_domain_model_tag');
    }
}
