Neos:
  Neos:
    modules:
      management:
        submodules:
          tagmanager:
            label: 'Wegmeister.TagManager:Modules:tagmanager.label'
            controller: '\Wegmeister\TagManager\Controller\TagController'
            description: 'Wegmeister.TagManager:Modules:tag.description'
            icon: icon-tags
            privilegeTarget: 'Wegmeister.TagManager:Backend.TagActions'

    userInterface:
      inspector:
        dataTypes:
          'Wegmeister\TagManager\Domain\Model\Tag':
            typeConverter: 'Neos\Neos\TypeConverter\EntityToIdentityConverter'
            editor: Neos.Neos/Inspector/Editors/SelectBoxEditor
            editorOptions:
              dataSourceIdentifier: 'wegmeister-tagmanager-tags'
              dataSourceAdditionalData:
                extended: true
      translation:
        # Configure which localization sources should be automatically included.
        # The included sources are parsed into the xliff.json which is loaded by Neos
        # for handling translations in the javascript code.
        #
        # Format:
        #   'Package.Key': ['Main', 'Errors', 'NodeTypes/*']
        autoInclude:
          'Wegmeister.TagManager': ['Main', 'Modules', 'NodeTypes/*']
