TYPO3:
  Neos:
    modules:
      management:
        submodules:
          tagmanager:
            label: 'Wegmeister.TagManager:Modules:tagmanager.label'
            controller: '\Wegmeister\TagManager\Controller\TagController'
            description: 'Wegmeister.TagManager:Modules:tag.description'
            icon: icon-font
            privilegeTarget: 'Wegmeister.TagManager:Backend.TagActions'

    userInterface:
      translation:
        # Configure which localization sources should be automatically included.
        # The included sources are parsed into the xliff.json which is loaded by Neos
        # for handling translations in the javascript code.
        #
        # Format:
        #   'Package.Key': ['Main', 'Errors', 'NodeTypes/*']
        autoInclude:
          'Wegmeister.TagManager': ['Main', 'Modules', 'NodeTypes/*']
